version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./packages/client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl/certs/fifteen_puzzle.pem
      - ./etc/ssl/fifteen_puzzle_key.pem
    ports:
      - 80:80
    depends_on:
      - server
  postgres:
    image: postgres:14     
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
  server:
    container_name: server
    image: prackicum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - postgres
    restart: always

